### ISSUE TITLE
Chrome: TypeError: Jr.toReversed is not a function

### ISSUE THREAD

**Issue by Leslie-Wong-H** [jasonlong/isometric-contributions#248]
Chrome Version: Version 107.0.5304.88 (Official Build) (64-bit)
```
Uncaught (in promise) TypeError: Jr.toReversed is not a function
    at iso.js:229:29
    at An (iso.js:418:3)
    at o (iso.js:442:5)
    at s (tslib.es6.js:147:23)
    at Object.next (tslib.es6.js:128:53)
    at a (_async_to_generator.mjs:3:20)
    at i (_async_to_generator.mjs:25:9)
```
![image](https://user-images.githubusercontent.com/27696701/233779797-1d26f33e-656c-466a-b1f1-b99a6c7b36c9.png)

![image](https://user-images.githubusercontent.com/27696701/233779807-24c9d611-0b86-47fa-a4ba-4742735b512f.png)

**Comment by Leslie-Wong-H** [comment]
Chrome auto-updated to Version 112.0.5615.138 (Official Build) (64-bit). Now it functions.  Strangely enough.
